services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ../config.yaml:/app/config.yaml